from PySide6.QtWidgets import QCheckBox, QHBoxLayout, QPlainTextEdit, QSizePolicy, QVBoxLayout, QWidget

from screen_qq_ocr.ui.widgets.controls import Card, ComboBox, TaskSelector, button, label
from screen_qq_ocr.ui.widgets.preview import Preview


class MonitorPage(QWidget):
    def __init__(self):
        super().__init__()
        layout = QVBoxLayout(self)
        layout.setSpacing(12)
        row = QHBoxLayout()
        row.addWidget(label("监控任务", "section"))
        row.addStretch()
        self.add_task = button("新建任务", True, "plus")
        self.remove_task = button("删除任务")
        self.stop_all = button("停止全部")
        for widget in (self.remove_task, self.stop_all, self.add_task):
            row.addWidget(widget)
        layout.addLayout(row)
        self.tasks = TaskSelector()
        layout.addWidget(self.tasks)
        content = QHBoxLayout()
        content.setSpacing(14)
        preview_card = Card("画面预览")
        source = QHBoxLayout()
        self.sources = ComboBox()
        self.refresh = button("刷新", glyph="refresh")
        self.select = button("使用来源")
        source.addWidget(self.sources, 1)
        source.addWidget(self.refresh)
        source.addWidget(self.select)
        preview_card.body.addLayout(source)
        self.preview = Preview()
        self.preview.editable = False
        preview_card.body.addWidget(self.preview, 1)
        actions = QHBoxLayout()
        self.pick_roi = button("选择监控区域", glyph="crop")
        self.pick_image_roi = button("选择截图区域", glyph="crop")
        self.clear_roi = button("重置监控区域", glyph="crop")
        self.clear_image_roi = button("重置截图区域", glyph="crop")
        self.once = button("识别一次")
        for widget in (self.pick_roi, self.pick_image_roi, self.clear_roi, self.clear_image_roi, self.once):
            actions.addWidget(widget)
        actions.addStretch()
        preview_card.body.addLayout(actions)
        content.addWidget(preview_card, 3)
        inspector = QVBoxLayout()
        options = Card("监控内容")
        self.keywords = QCheckBox("关键词检测")
        self.keywords.setChecked(True)
        self.flash = QCheckBox("色块报警")
        self.flash_state = label("色块：未启用")
        for widget in (self.keywords, self.flash, self.flash_state):
            options.body.addWidget(widget)
        actions = QHBoxLayout()
        self.start = button("开始监控", True)
        self.stop = button("停止")
        actions.addWidget(self.start)
        actions.addWidget(self.stop)
        options.body.addLayout(actions)
        inspector.addWidget(options)
        results = Card("最近识别")
        self.ocr = QPlainTextEdit()
        self.ocr.setReadOnly(True)
        self.ocr.setPlaceholderText("识别结果将在这里显示")
        self.ocr.setMinimumWidth(150)
        self.ocr.setMinimumHeight(64)
        self.ocr.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Ignored)
        self.meta = label("尚无识别结果")
        results.body.addWidget(self.ocr, 1)
        results.body.addWidget(self.meta)
        inspector.addWidget(results, 1)
        content.addLayout(inspector, 2)
        layout.addLayout(content, 1)
        pending_card = Card()
        pending_row = QHBoxLayout()
        pending_row.addWidget(label("通知队列", "section"))
        self.pending = label("无待发送任务")
        pending_row.addWidget(self.pending, 1)
        self.cancel = button("取消待发送")
        pending_row.addWidget(self.cancel)
        pending_card.body.addLayout(pending_row)
        layout.addWidget(pending_card)
