from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QFormLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)

from screen_qq_ocr.ui.widgets.controls import Button as QPushButton
from screen_qq_ocr.ui.widgets.controls import Card
from screen_qq_ocr.ui.widgets.controls import ComboBox as QComboBox


class QQPage(QWidget):
    def __init__(self):
        super().__init__()
        layout = QVBoxLayout(self)
        tabs = QTabWidget()
        layout.addWidget(tabs)
        connection = QWidget()
        form = QFormLayout(connection)
        self.url = QLineEdit("ws://127.0.0.1:3001")
        self.token = QLineEdit()
        self.token.setEchoMode(QLineEdit.EchoMode.Password)
        self.connect = QPushButton("连接并核验")
        self.connect.setProperty("variant", "primary")
        self.disconnect = QPushButton("断开连接")
        self.account = QLabel("未连接")
        self.account.setWordWrap(True)
        form.addRow("OneBot 正向 WS", self.url)
        form.addRow("消息通道凭据", self.token)
        form.addRow(self.connect)
        form.addRow(self.disconnect)
        form.addRow(self.account)
        tabs.addTab(connection, "消息连接")
        login = QWidget()
        login_layout = QVBoxLayout(login)
        shell_form = QFormLayout()
        self.launcher = QLineEdit()
        self.launcher.setPlaceholderText("NapCat 启动文件")
        self.browse_launcher = QPushButton("选择启动文件")
        launcher_row = QHBoxLayout()
        launcher_row.addWidget(self.launcher, 1)
        launcher_row.addWidget(self.browse_launcher)
        shell_form.addRow("NapCat Shell", launcher_row)
        self.config_dir = QLineEdit()
        self.config_dir.setPlaceholderText("NapCat config 目录")
        self.browse_config = QPushButton("选择配置目录")
        config_row = QHBoxLayout()
        config_row.addWidget(self.config_dir, 1)
        config_row.addWidget(self.browse_config)
        shell_form.addRow("配置目录", config_row)
        self.onebot_config = QComboBox()
        self.onebot_config.addItem("onebot11.json")
        shell_form.addRow("账号 OneBot 配置", self.onebot_config)
        shell_actions = QHBoxLayout()
        self.start_shell = QPushButton("启动 NapCat")
        self.start_shell.setProperty("variant", "primary")
        self.read_tokens = QPushButton("读取配置")
        shell_actions.addWidget(self.start_shell)
        shell_actions.addWidget(self.read_tokens)
        self.stop_shell = QPushButton("停止 NapCat")
        self.shell_status = QLabel("未启动")
        self.shell_status.setWordWrap(True)
        login_form = QFormLayout()
        self.management_url = QLineEdit("http://127.0.0.1:6099")
        self.management_token = QLineEdit()
        self.management_token.setEchoMode(QLineEdit.EchoMode.Password)
        login_form.addRow("本机管理地址", self.management_url)
        login_form.addRow("管理端凭据", self.management_token)
        self.management_url.hide()
        self.management_token.hide()
        buttons = QHBoxLayout()
        self.login = QPushButton("启动并显示二维码")
        self.login.setProperty("variant", "primary")
        self.refresh_qr = QPushButton("刷新二维码")
        buttons.addWidget(self.login)
        buttons.addWidget(self.refresh_qr)
        login_layout.addLayout(buttons)
        self.qr = QLabel("登录二维码")
        self.qr.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.qr.setMinimumHeight(150)
        login_layout.addWidget(self.qr)
        self.login_status = QLabel("未登录")
        self.login_status.setWordWrap(True)
        login_layout.addWidget(self.login_status)
        tabs.addTab(login, "运行与登录")
        # Reuse the connected controls in two concise runtime cards.
        overview = QWidget()
        columns = QHBoxLayout(overview)
        shell_card = Card("NapCat Shell")
        shell_fields = QFormLayout()
        shell_fields.setRowWrapPolicy(QFormLayout.RowWrapPolicy.WrapAllRows)
        shell_form.removeItem(launcher_row)
        shell_fields.addRow("启动文件", launcher_row)
        shell_form.removeItem(config_row)
        shell_fields.addRow("配置目录", config_row)
        shell_fields.addRow("账号配置", self.onebot_config)
        shell_card.body.addLayout(shell_fields)
        for widget in (self.start_shell, self.read_tokens, self.stop_shell, self.shell_status):
            shell_card.body.addWidget(widget)
        shell_card.body.addStretch()
        channel = Card("消息连接")
        channel_fields = QFormLayout()
        channel_fields.setRowWrapPolicy(QFormLayout.RowWrapPolicy.WrapAllRows)
        channel_fields.addRow("OneBot 正向 WebSocket", self.url)
        channel_fields.addRow("消息通道凭据", self.token)
        channel.body.addLayout(channel_fields)
        self.connect.setText("连接并核验")
        self.disconnect.setText("断开消息连接")
        self.stop_shell.setText("停止 NapCat")
        self.read_tokens.setText("读取配置")
        for widget in (self.connect, self.disconnect, self.account):
            channel.body.addWidget(widget)
        channel.body.addStretch()
        columns.addWidget(shell_card, 1)
        columns.addWidget(channel, 1)
        tabs.removeTab(0)
        tabs.insertTab(0, overview, "连接与运行")
        tabs.setTabText(1, "QQ 登录")
        tabs.setCurrentIndex(0)
